# Generated by Django 4.1.7 on 2023-04-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name_of_the_shop', models.CharField(max_length=100)),
                ('name_of_the_owner', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('local_area_address', models.CharField(max_length=100)),
                ('land_mark', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=1)),
                ('shop_image', models.ImageField(upload_to='uploads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopdetails', to='shops.category')),
            ],
            options={
                'ordering': ('-name_of_the_shop',),
            },
        ),
    ]
