# Generated by Django 4.1.7 on 2023-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopdetails',
            options={},
        ),
        migrations.RemoveField(
            model_name='shopdetails',
            name='shop_image',
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='products',
            field=models.ManyToManyField(to='product.product'),
        ),
        migrations.RemoveField(
            model_name='shopdetails',
            name='category',
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='category',
            field=models.ManyToManyField(to='product.category'),
        ),
    ]
