# Generated by Django 4.1.7 on 2023-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shopdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopdetails',
            options={'ordering': ('-name_of_the_shop',)},
        ),
        migrations.RemoveField(
            model_name='shopdetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shopdetails',
            name='products',
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('shops', models.ManyToManyField(to='shops.shopdetails')),
            ],
        ),
    ]
